server.port=7070
spring.application.name=api-gateway

# Eureka
eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.preferIpAddress=true

# Discovery locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Global CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
management.endpoints.web.exposure.include=*

# Swagger UI — ONLY these, no duplicates
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.use-root-path=true
springdoc.swagger-ui.urls[0].name=user-service
springdoc.swagger-ui.urls[0].url=/users/v3/api-docs
springdoc.swagger-ui.urls[1].name=group-service
springdoc.swagger-ui.urls[1].url=/groups/v3/api-docs
springdoc.swagger-ui.urls[2].name=auth-service
springdoc.swagger-ui.urls[2].url=/api/auth/v3/api-docs
springdoc.swagger-ui.urls[3].name=mentor-service
springdoc.swagger-ui.urls[3].url=/mentors/v3/api-docs
springdoc.swagger-ui.urls[4].name=notification-service
springdoc.swagger-ui.urls[4].url=/notification-service/v3/api-docs
springdoc.swagger-ui.urls[5].name=review-service
springdoc.swagger-ui.urls[5].url=/reviews/v3/api-docs
springdoc.swagger-ui.urls[6].name=skill-service
springdoc.swagger-ui.urls[6].url=/skills/v3/api-docs
