server.port=7070

spring.application.name=api-gateway

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Global CORS Configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.preferIpAddress=true

# Swagger UI Config
springdoc.swagger-ui.urls[0].name=user-service
springdoc.swagger-ui.urls[0].url=/user-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=group-service
springdoc.swagger-ui.urls[1].url=/group-service/v3/api-docs

springdoc.swagger-ui.urls[2].name=session-service
springdoc.swagger-ui.urls[2].url=/session-service/v3/api-docs

springdoc.swagger-ui.urls[3].name=skill-service
springdoc.swagger-ui.urls[3].url=/skill-service/v3/api-docs

springdoc.swagger-ui.urls[4].name=notification-service
springdoc.swagger-ui.urls[4].url=/notification-service/v3/api-docs

springdoc.swagger-ui.urls[5].name=review-service
springdoc.swagger-ui.urls[5].url=/review-service/v3/api-docs

springdoc.swagger-ui.urls[6].name=authentication-service
springdoc.swagger-ui.urls[6].url=/authentication-service/v3/api-docs

springdoc.swagger-ui.urls[7].name=mentor-service
springdoc.swagger-ui.urls[7].url=/mentor-service/v3/api-docs

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


