#Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka


#Oracle
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@//host.docker.internal:1521/xe
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
#spring.datasource.username=scott
#spring.datasource.password=tiger

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CORRECT FOR HIBERNATE 7
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#For docker
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# tracing settings added by script
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
