eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Lombok Logging (Console and File Appender)
logging.file.name=logs/application.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
