spring.application.name=group-service
feign.circuitbreaker.enabled=true
server.port=7077

# tracing settings added by script
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

