spring.application.name=mentor-service
server.port=7073
spring.jpa.properties.hibernate.id.optimizer.pooled.preferred=none

# tracing settings added by script
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

springdoc.api-docs.path=/mentors/v3/api-docs
